### ISSUE TITLE
Installation issues with Debian 9 and itsbc

### ISSUE THREAD

**Issue by atuxnull** [irontec/itsbc#15]
Running Debian 9 in a VM and i cannot install itsbc mini by following https://blog.irontec.com/irontec-tiny-sbc/ i am getting the following errors:
```

root@debian: ~ $ apt-get install itsbc
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 itsbc : Depends: itsbc-rtpengine but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
root@debian: ~ $
```

`root@debian: ~ $ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.12 (stretch)
Release:        9.12
Codename:       stretch
root@debian: ~ $ uname -a
Linux debian 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux
root@debian: ~ $
`

Any ideas, please?

**Comment by Kaian** [comment]
Hi @atuxnull 

itsbc-rtpengine package had a dependency on an old kernel that I have updated in the above commit. 

You should be able to `apt-get update` and `apt-get install itsbc` now without problems.

Take into account that we don't offer any kind of support for this product, but at least it should be installable, so thanks a lot for reporting!

Regards!
