### ISSUE TITLE
Some phone models answer "Not Found" to the options

### ISSUE THREAD

**Issue by ralonsom** [irontec/itsbc#9]
After registering several types of phones, we observed that Alcatel terminals, when they receive an option that passes through the TinySBC, answers Not Found

[optionsNotFound.zip](https://github.com/irontec/itsbc/files/2035300/optionsNotFound.zip)

**Comment by ralonsom** [comment]
I've seen that the problem comes in  "OPTIONS sip:103@lookup:24123;transport=udp SIP/2.0" alcatel terminals don't like the "lookup", I made a little modification to confirm it:
```
    if (is_method("OPTIONS")){
        $ru='sip:' + $rU + '@' + $dd + ':' + $dp + ';transport='+ $dP;
        xlog("L_NOTICE", "NOTICE: Change ru to $ru for Alcatel phones \n");
    }
```
y funciona bien.

**Comment by cruzccl** [comment]
I think there is a problem in the logic of route 'initialrequest' or the contents of database for given peer.

Could you please paste here the results of the query:

```
SELECT routing_requests.handleRtp, routing_requests.incomingRtpInterface_id, routing_requests.outgoingRtpInterface_id, routing_requests.redOrigen, routing_requests.nextHopTransport, routing_requests.nextHop, CONCAT(routing_requests.nextHop, ':', routing_requests.nextHopPort) AS destino, CONCAT(routing_requests.nextHopTransport, ':', routing_requests.ipSalida, ':', routing_requests.portSalida) AS ifacesalida FROM routing_requests WHERE ipEntrada='192.168.38.187' AND domain='192.168.38.187' ORDER BY metrica ASC LIMIT 1;
```

Regards,

**Comment by ralonsom** [comment]
`
+-----------+-------------------------+-------------------------+----------------------------+------------------+---------+-------------+-------------------------+
| handleRtp | incomingRtpInterface_id | outgoingRtpInterface_id | redOrigen                  | nextHopTransport | nextHop | destino     | ifacesalida             |
+-----------+-------------------------+-------------------------+----------------------------+------------------+---------+-------------+-------------------------+
|         0 |                       3 |                       2 | 192.168.38.0/255.255.255.0 | UDP              | lookup  | lookup:4060 | UDP:192.168.38.187:4060 |
+-----------+-------------------------+-------------------------+----------------------------+------------------+---------+-------------+-------------------------+
`

**Comment by cruzccl** [comment]
We think this commit 8c77ff76777453968ef3fe588dd8f6633e0a5cf3 should solve the issue.

Could you please update and test it?

Thanks and regards,

**Comment by ralonsom** [comment]
Yep, work correctly now
